name: publish

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: {node-version: 10.x}
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
        restore-keys: ${{runner.os}}-node-
    - run: "npm ci"
    - run: "npm run build:pub"
    - run: "git fetch --all"
    - run: "git switch hostme"
    - run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
    - run: "git merge --strategy-option=ours"
    - run: "git add -A"
    - run: "git add bundleOutput"
    - run: "git commit -m 'ci: publish'"
    # https://stackoverflow.com/questions/36782467/set-subdirectory-as-website-root-on-github-pages
    - run: "git subtree push --prefix bundleOutput origin hostme"
